### ISSUE TITLE
pysqlite3 problem - not supporting PEP 517 builds

### ISSUE THREAD

**Issue by zepef** [onepointconsulting/data-questionnaire-agent#1]
Hello,

I run into install problems on Windows as well as on Ubuntu:

[data-questionnaire-agent.txt](https://github.com/onepointconsulting/data-questionnaire-agent/files/13608848/data-questionnaire-agent.txt)

I really would like to test your app which looks really outstanding.

All the best,

Pierre-Emmanuel

**Comment by onepointconsulting** [comment]
Hello, the reason for this problem seems to be that `gcc` is not installed on the Linux system. 

This is the error message I saw in your logs:

`error: command 'gcc' failed: No such file or directory`

I suggest to execute these three commands:

```bash
sudo apt update
sudo apt install build-essential
# Check if gcc is installed
gcc --version
```

**Comment by onepointconsulting** [comment]
The problem seems to be solved by installing gcc. @zepef could install the packages after installing gcc.
