### ISSUE TITLE
Install OK but now error at runtime

### ISSUE THREAD

**Issue by zepef** [onepointconsulting/data-questionnaire-agent#2]
Thanks a lot for your advice. I created an Ubuntu instance from scratch (20.04) and went through the whole install process. No error encountered during install but script can't be run with chainlit run .\data_questionnaire_agent\ui\data_questionnaire_chainlit.py --port 8080.

[data-questionnaire-agent.txt](https://github.com/onepointconsulting/data-questionnaire-agent/files/13613429/data-questionnaire-agent.txt)

Best regards,

Pierre-Emmanuel

**Comment by onepointconsulting** [comment]
Hello,

please make sure that you have a `.env` file at the root of your folder. with a REQUEST_TIMEOUT property. Please check the project README for more information.
